# Site settings
title:
email: synthpatrol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "synthpatrol.space" # the base hostname & protocol for your site

twitter_username:
github_username: JeanBombeur45

# Build settings
markdown: kramdown
